### PR TITLE
French translations delivery

### PR DESCRIPTION
**Pull request by 111studio**
Hi,

While compiling with pybabel, we had the following warning : 

```
pybabel compile -d . -l fr
error: ./fr/LC_MESSAGES/messages.po:10749: incompatible format for placeholder 1: 'o' and 'd' are not compatible
compiling catalog './fr/LC_MESSAGES/messages.po' to './fr/LC_MESSAGES/messages.mo'
```

I believe it's due to having a % ("(ie, \"buy 1 get 1 free\"; \"x% off\"; etc...).") inside the translation key, can you confirm we should leave it as is ?

### CODE REVIEW

**Comment by deleteme** [comment]
Yeah I also encountered that same warning. Nothing is wrong with the string that I can tell. It could be a bug in pybabel.

**Comment by deleteme** [comment]
@111studio It appears the French message po files are outdated. They still include all of the errors I fixed in #59. I also just fixed another syntax error in #71 that needs to be in this. These files cannot be accepted until they include these fixes.

**Comment by 111studio** [comment]
Hi Matt,

I just fixed all the errors reported in #59 and #71 

Kind regards,

**Comment by antolen** [comment]
Thanks for your translations, I merged them manually.

**Pull request closed without merging**
